name: Mingw build testing

on: [push, pull_request]
jobs:
  build-mingw:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          pacman -Syu mingw-w64-gcc meson python-mako glslang mingw-w64-headers git --noconfirm
      - name: configure
        run: meson setup --cross-file mingw64.txt build64
      - name: build
        run: ninja -C build64